import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import {
  iranSans,
  iranYekanWebLight,
  iranYekanWebRegular,
} from '@/app/_fonts/font';
import Header from '@/components/Global/Header';
import Providers from '@/components/Providers/Providers';
import { ViewTransitions } from 'next-view-transitions';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="fa" suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} ${iranSans.variable} ${iranYekanWebLight.variable} ${iranYekanWebRegular.variable} antialiased !bg-background`}
        >
          <Providers>
            <Header />
            {children}
          </Providers>
        </body>
      </html>
    </ViewTransitions>
  );
}
